; PlatformIO Project Configuration File for Arduino Nano Robot Bridge
;

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200


lib_deps = 
    adafruit/Adafruit Motor Shield V2 Library